FROM cgr.dev/chainguard/python:latest-dev AS build
WORKDIR /app
COPY apps/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM cgr.dev/chainguard/python:latest
COPY --from=build /usr/lib/python3 /usr/lib/python3
COPY --from=build /app /app
COPY apps/backend /app
WORKDIR /app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
